export const kpiCards = [
  {
    id: 'total-assets',
    icon: 'Boxes',
    label: 'Total Assets',
    value: '2,486',
    position: 'top-[12%] left-[8%]',
    animationClass: 'animate-float-slow',
    delay: '0s',
  },
  {
    id: 'allocated-assets',
    icon: 'CheckCircle2',
    label: 'Allocated Assets',
    value: '1,982',
    position: 'top-[22%] right-[10%]',
    animationClass: 'animate-float-medium',
    delay: '1.5s',
  },
  {
    id: 'available-assets',
    icon: 'PackageCheck',
    label: 'Available Assets',
    value: '504',
    position: 'bottom-[35%] left-[6%]',
    animationClass: 'animate-float-fast',
    delay: '0.8s',
  },
  {
    id: 'maintenance',
    icon: 'Wrench',
    label: 'Under Maintenance',
    value: '38',
    position: 'bottom-[12%] right-[12%]',
    animationClass: 'animate-float-slow',
    delay: '2.2s',
  },
  {
    id: 'active-employees',
    icon: 'Users',
    label: 'Active Employees',
    value: '648',
    position: 'top-[52%] left-[40%]',
    animationClass: 'animate-float-medium',
    delay: '3s',
  },
];
